### ISSUE TITLE
Default Recitation 4 - summary is not consistent with problems listed below

### ISSUE THREAD

**Issue by annagodin** [Joeb3219/dynrec-issues#15]
**Describe the bug**
The recitation summary says that the problems should be:
Leap Years, Speeding Tickets, Summation of first x Numbers, Horizontal Pyramid, Vertical Pyramid

However, the problems below are:
Can you vote?, Speeding Tickets, Summation of first x Numbers, Horizontal Pyramid, Leap Years

**To Reproduce**
1. Go to Lesson Plans
2. Click on Default Recitation 4
3. Observe the summary with time estimates
4. Scroll down to where the problems are
5. observe that the problems are not consistent with the summary

**Expected behavior**
Expect problems listed to be consistent with the summary of what the problems should be

**User (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser Chrome
 - Version [e.g. 22] - idk

**Comment by Joeb3219** [comment]
Thanks for pointing that out, fixed.
