### ISSUE TITLE
Printable Roster from Manage Roster Page

### ISSUE THREAD

**Issue by CutlerRU** [Joeb3219/dynrec-issues#17]
**Describe the feature you'd like**
I would like to have the feature to download and print out the roster for each section. This could be useful as a sign in sheet for each recitation. Perhaps have a printing icon that will download the roster as a nicely formatted pdf for a sign in sheet.

**Additional context**
This is what the current printing situation looks like, I would want just the names and possible a signature column.
![image](https://user-images.githubusercontent.com/15910085/46035879-228aff80-c0d2-11e8-9e0d-3875077cbb36.png)

**Comment by Joeb3219** [comment]
Implemented in commit 3778aa7fe388e4edaa9a2915cd7ff1e506bfdb76
