### ISSUE TITLE
The spelling service was not found: (undefined)

### ISSUE THREAD

**Issue by CutlerRU** [Joeb3219/dynrec-issues#5]
**Bug Description**
The spellcheck feature in the "new problem" description does not function.

**To Reproduce**
1. Go to Problems
2. Click on "New Problem"
3. Scroll down to "Problem Description"
4. Click on "Spellcheck"
5. See error "The spelling service was not found: (undefined)"

**Expected behavior**
I wanted the spellchecker to tell me if there were any typos in the description of the problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/15910085/45435871-74b63480-b67f-11e8-9b31-c04340733f7f.png)

**User (please complete the following information):**
 - OS: ChromeOS 
 - Browser: Chrome 
 - Version: Version 69.0.3497.73 (Official Build) beta (64-bit)

**Comment by Joeb3219** [comment]
This appears to be caused by requiring a paid service with our configuration.

**Comment by Joeb3219** [comment]
I've disabled spellchecker, and instead enabled browser level spell-checking. You'll see redlines under unknown words, and can change them based on browser dictionary.

Implemented in commit 9328d46c94935ac051248aaf2b5c40791ca13e30
