### ISSUE TITLE
User search function not finding users

### ISSUE THREAD

**Issue by CutlerRU** [Joeb3219/dynrec-issues#6]
**Describe the bug**
When using the search for user function, searching for a known user returns "No user found by the given NetID."

**To Reproduce**
1. Go to User Search
2. Type in the NetID of a known user.
3. Run the search.
4. See error "No user found by the given NetID."

**Expected behavior**
I expect the search to find the user with the given NetID.

**Screenshots**
![image](https://user-images.githubusercontent.com/15910085/45436360-a24fad80-b680-11e8-9656-e573c1d3894b.png)

**User (please complete the following information):**
 - OS: ChromeOS
 - Browser: Chrome
 - Version: Version 69.0.3497.73 (Official Build) beta (64-bit)

**Additional context**

**Comment by Joeb3219** [comment]
Can you verify that searching for other users (your students) works? I believe the problem is that you're not a student in the course.

If so, I should remove non-students from this page's listings.

**Comment by CutlerRU** [comment]
![image](https://user-images.githubusercontent.com/15910085/45444674-1c3e6180-b696-11e8-9211-8dec35d5f2d0.png)

It lists me as a searchable user. I assume that this is what you are referring to about removing from page listings.

**Comment by Joeb3219** [comment]
Right. I'll do that now.

**Comment by Joeb3219** [comment]
Implemented in commit 7007f050ce0729fe05459bd9a6d10395422710a0
