### ISSUE TITLE
Reorganize Recitations

### ISSUE THREAD

**Issue by AbdallAhmed** [Joeb3219/dynrec-issues#7]
**Describe the feature you'd like**
On the recitation page, as well as the homepage, have it such that the recitations appear in order by date & time. Right now it seems they appear in order of recitation number (when you hit the recitation tab this is definitely the case).

**Additional context**
Having the choice in which order to list it is probably the best case scenario.

**Comment by Joeb3219** [comment]
Implemented in commit fea7917db36a12b59466fb84746b12e23ef0ce9b
